### ISSUE TITLE
scopes parameter should be scope

### ISSUE THREAD

**Issue by gotpist1** [gardner/react-oauth2-pkce#5]
The uri that generates from AuthServiceProps is wrong. It should be scope, note scopes. At least that is what i have found out  :)

**Comment by TheSpivack** [comment]
> The uri that generates from AuthServiceProps is wrong. It should be scope, note scopes. At least that is what i have found out :)

I discovered the same issue

**Comment by TheSpivack** [comment]
I created [Pull Request 6](https://github.com/gardner/react-oauth2-pkce/pull/6) to resolve this

**Comment by gardner** [comment]
This has been merged
