### ISSUE TITLE
Can this be used with Next JS?

### ISSUE THREAD

**Issue by yelnyaface** [gardner/react-oauth2-pkce#7]
hi, am new to this,
can this be used with `nextJS`?

**Comment by gardner** [comment]
I have never used it with nextjs. Please let me now if you are successful. Thanks

**Comment by frco9** [comment]
It's working for me using `dynamic` imports and a a custom component as described here : https://github.com/AxaGuilDEv/react-oidc/issues/546#issuecomment-835426334
